package main
//
//import (
//	"encoding/json"
//	"fmt"
//	"strings"
//	"time"
//)
//
//type AutoGenerated struct {
//	Took         int          `json:"took"`
//	TimedOut     bool         `json:"timed_out"`
//	Shards       Shards       `json:"_shards"`
//	ParentHits       ParentHits         `json:"parent_hits"`
//	Aggregations Aggregations `json:"aggregations"`
//}
//type Shards struct {
//	Total      int `json:"total"`
//	Successful int `json:"successful"`
//	Skipped    int `json:"skipped"`
//	Failed     int `json:"failed"`
//}
//type Total struct {
//	Value    int    `json:"value"`
//	Relation string `json:"relation"`
//}
//type CPU struct {
//	HrProcessorFrwID string `json:"hrProcessorFrwID"`
//	HrProcessorLoad  string `json:"hrProcessorLoad"`
//}
//type Health struct {
//	MtxrHIVoltage     string `json:"mtxrHIVoltage"`
//	MtxrHITemperature string `json:"mtxrHITemperature"`
//}
//type System struct {
//	SysDescr    string `json:"sysDescr"`
//	SysObjectID string `json:"sysObjectID"`
//	SysUpTime   string `json:"sysUpTime"`
//	SysContact  string `json:"sysContact"`
//	SysName     string `json:"sysName"`
//}
//type Stats struct {
//	IfAlias              string `json:"ifAlias"`
//	IfHCOutOctets        string `json:"ifHCOutOctets"`
//	IfHCOutUcastPkts     string `json:"ifHCOutUcastPkts"`
//	IfHCInMulticastPkts  string `json:"ifHCInMulticastPkts"`
//	IfHighSpeed          string `json:"ifHighSpeed"`
//	IfName               string `json:"ifName"`
//	IfHCOutBroadcastPkts string `json:"ifHCOutBroadcastPkts"`
//	IfHCInOctets         string `json:"ifHCInOctets"`
//	IfHCInUcastPkts      string `json:"ifHCInUcastPkts"`
//	IfHCInBroadcastPkts  string `json:"ifHCInBroadcastPkts"`
//	IfHCOutMulticastPkts string `json:"ifHCOutMulticastPkts"`
//}
//type Address struct {
//	IPAdEntNetMask string `json:"ipAdEntNetMask"`
//	IPAdEntAddr    string `json:"ipAdEntAddr"`
//	IPAdEntIfIndex string `json:"ipAdEntIfIndex"`
//}
//type Interfaces struct {
//	IfOutOctets   string    `json:"ifOutOctets"`
//	Stats         Stats     `json:"stats"`
//	IfPhysAddress string    `json:"ifPhysAddress"`
//	IfInOctets    string    `json:"ifInOctets"`
//	Ts            time.Time `json:"ts"`
//	IfOperStatus  string    `json:"ifOperStatus"`
//	IfMtu         string    `json:"ifMtu"`
//	Address       Address   `json:"address,omitempty"`
//	IfSpeed       string    `json:"ifSpeed"`
//	IfAdminStatus string    `json:"ifAdminStatus"`
//	IfLastChange  string    `json:"ifLastChange"`
//	IfDescr       string    `json:"ifDescr"`
//	IfIndex       string    `json:"ifIndex"`
//	IfType        string    `json:"ifType"`
//}
//type Storage struct {
//	HrStorageDescr              string    `json:"hrStorageDescr"`
//	HrStorageAllocationUnits    string    `json:"hrStorageAllocationUnits"`
//	HrStorageSize               string    `json:"hrStorageSize"`
//	HrStorageUsed               string    `json:"hrStorageUsed"`
//	HrStorageAllocationFailures string    `json:"hrStorageAllocationFailures"`
//	Ts                          time.Time `json:"ts"`
//	HrStorageIndex              string    `json:"hrStorageIndex"`
//	HrStorageType               string    `json:"hrStorageType"`
//}
//type Source struct {
//	Timestamp  time.Time    `json:"@timestamp"`
//	Type       string       `json:"type"`
//	SnmpHost   string       `json:"snmp.host"`
//	CPU        []CPU        `json:"cpu"`
//	Health     Health       `json:"health"`
//	System     System       `json:"system"`
//	Interfaces []Interfaces `json:"interfaces"`
//	Storage    []Storage    `json:"storage"`
//}
//type Hits struct {
//	Index  string  `json:"_index"`
//	Type   string  `json:"_type"`
//	ID     string  `json:"_id"`
//	Score  float64 `json:"_score"`
//	Source Source  `json:"_source"`
//}
//type ParentHits struct {
//	Total    Total   `json:"total"`
//	MaxScore float64 `json:"max_score"`
//	Hits     []Hits  `json:"hits"`
//}
//type OutOctets struct {
//	Value float64 `json:"value"`
//}
//type TotalBandwidth struct {
//	Value float64 `json:"value"`
//}
//type InOctets struct {
//	Value float64 `json:"value"`
//}
//type AsDifferenceIn struct {
//	Value float64 `json:"value"`
//}
//type AsDifferenceOut struct {
//	Value float64 `json:"value"`
//}
//type Buckets struct {
//	KeyAsString     time.Time       `json:"key_as_string"`
//	Key             int64           `json:"key"`
//	DocCount        int             `json:"doc_count"`
//	OutOctets       OutOctets       `json:"outOctets"`
//	TotalBandwidth  TotalBandwidth  `json:"totalBandwidth"`
//	InOctets        InOctets        `json:"inOctets"`
//	AsDifferenceIn  AsDifferenceIn  `json:"as_difference_in,omitempty"`
//	AsDifferenceOut AsDifferenceOut `json:"as_difference_out,omitempty"`
//}
//type MyGraph struct {
//	Buckets []Buckets `json:"buckets"`
//}
//type SmallBuckets struct {
//	Key      string  `json:"key"`
//	DocCount int     `json:"doc_count"`
//	MyGraph  MyGraph `json:"my_graph"`
//}
//type ByInterfaces struct {
//	DocCountErrorUpperBound int       `json:"doc_count_error_upper_bound"`
//	SumOtherDocCount        int       `json:"sum_other_doc_count"`
//	SmallBuckets            []SmallBuckets `json:"buckets"`
//}
//type GetNestedInterfaces struct {
//	DocCount     int          `json:"doc_count"`
//	ByInterfaces ByInterfaces `json:"by_interfaces"`
//}
//type Aggregations struct {
//	GetNestedInterfaces GetNestedInterfaces `json:"get_nested_interfaces"`
//}
//func main() {
//	res := `{
//  "took" : 3,
//  "timed_out" : false,
//  "_shards" : {
//    "total" : 2,
//    "successful" : 2,
//    "skipped" : 0,
//    "failed" : 0
//  },
//  "aggregations" : {
//    "get_nested_interfaces" : {
//      "doc_count" : 150,
//      "by_interfaces" : {
//        "doc_count_error_upper_bound" : 0,
//        "sum_other_doc_count" : 50,
//        "buckets" : [
//          {
//            "key" : "BhaiFi-LAN",
//            "doc_count" : 10,
//            "my_graph" : {
//              "buckets" : [
//                {
//                  "key_as_string" : "2020-05-08T07:30:00.000Z",
//                  "key" : 1588923000000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 7.3077267E7
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 2.039783225E8
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:32:00.000Z",
//                  "key" : 1588923120000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 7.3093105E7
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 2.04021729E8
//                  },
//                  "as_difference_in" : {
//                    "value" : 43406.5
//                  },
//                  "as_difference_out" : {
//                    "value" : 15838.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:34:00.000Z",
//                  "key" : 1588923240000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 7.3105733E7
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 2.040679635E8
//                  },
//                  "as_difference_in" : {
//                    "value" : 46234.5
//                  },
//                  "as_difference_out" : {
//                    "value" : 12628.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:36:00.000Z",
//                  "key" : 1588923360000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 7.3119013E7
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 2.041126365E8
//                  },
//                  "as_difference_in" : {
//                    "value" : 44673.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 13280.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:38:00.000Z",
//                  "key" : 1588923480000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 7.3129783E7
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 2.041556225E8
//                  },
//                  "as_difference_in" : {
//                    "value" : 42986.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 10770.0
//                  }
//                }
//              ]
//            }
//          },
//          {
//            "key" : "BhaiFi-VPN",
//            "doc_count" : 10,
//            "my_graph" : {
//              "buckets" : [
//                {
//                  "key_as_string" : "2020-05-08T07:30:00.000Z",
//                  "key" : 1588923000000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 1.0903862E7
//                  },
//                  "totalBandwidth" : {
//                    "value" : 1.0E7
//                  },
//                  "inOctets" : {
//                    "value" : 2894925.5
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:32:00.000Z",
//                  "key" : 1588923120000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 1.0929618E7
//                  },
//                  "totalBandwidth" : {
//                    "value" : 1.0E7
//                  },
//                  "inOctets" : {
//                    "value" : 2902497.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 7571.5
//                  },
//                  "as_difference_out" : {
//                    "value" : 25756.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:34:00.000Z",
//                  "key" : 1588923240000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 1.0960573E7
//                  },
//                  "totalBandwidth" : {
//                    "value" : 1.0E7
//                  },
//                  "inOctets" : {
//                    "value" : 2910363.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 7866.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 30955.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:36:00.000Z",
//                  "key" : 1588923360000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 1.0991528E7
//                  },
//                  "totalBandwidth" : {
//                    "value" : 1.0E7
//                  },
//                  "inOctets" : {
//                    "value" : 2918229.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 7866.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 30955.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:38:00.000Z",
//                  "key" : 1588923480000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 1.1022506E7
//                  },
//                  "totalBandwidth" : {
//                    "value" : 1.0E7
//                  },
//                  "inOctets" : {
//                    "value" : 2926095.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 7866.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 30978.0
//                  }
//                }
//              ]
//            }
//          },
//          {
//            "key" : "Vlan10",
//            "doc_count" : 10,
//            "my_graph" : {
//              "buckets" : [
//                {
//                  "key_as_string" : "2020-05-08T07:30:00.000Z",
//                  "key" : 1588923000000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 2528314.5
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:32:00.000Z",
//                  "key" : 1588923120000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 2529064.5
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 750.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:34:00.000Z",
//                  "key" : 1588923240000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 2529814.5
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 750.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:36:00.000Z",
//                  "key" : 1588923360000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 2530564.5
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 750.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:38:00.000Z",
//                  "key" : 1588923480000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 2531314.5
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 750.0
//                  }
//                }
//              ]
//            }
//          },
//          {
//            "key" : "WAN1",
//            "doc_count" : 10,
//            "my_graph" : {
//              "buckets" : [
//                {
//                  "key_as_string" : "2020-05-08T07:30:00.000Z",
//                  "key" : 1588923000000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 1.52499907E8
//                  },
//                  "totalBandwidth" : {
//                    "value" : 1.0E9
//                  },
//                  "inOctets" : {
//                    "value" : 1.05203407E8
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:32:00.000Z",
//                  "key" : 1588923120000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 1.52563096E8
//                  },
//                  "totalBandwidth" : {
//                    "value" : 1.0E9
//                  },
//                  "inOctets" : {
//                    "value" : 1.0524351E8
//                  },
//                  "as_difference_in" : {
//                    "value" : 40103.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 63189.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:34:00.000Z",
//                  "key" : 1588923240000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 1.52630564E8
//                  },
//                  "totalBandwidth" : {
//                    "value" : 1.0E9
//                  },
//                  "inOctets" : {
//                    "value" : 1.05280998E8
//                  },
//                  "as_difference_in" : {
//                    "value" : 37488.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 67468.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:36:00.000Z",
//                  "key" : 1588923360000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 1.526989055E8
//                  },
//                  "totalBandwidth" : {
//                    "value" : 1.0E9
//                  },
//                  "inOctets" : {
//                    "value" : 1.05320018E8
//                  },
//                  "as_difference_in" : {
//                    "value" : 39020.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 68341.5
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:38:00.000Z",
//                  "key" : 1588923480000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 1.52763181E8
//                  },
//                  "totalBandwidth" : {
//                    "value" : 1.0E9
//                  },
//                  "inOctets" : {
//                    "value" : 1.05355371E8
//                  },
//                  "as_difference_in" : {
//                    "value" : 35353.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 64275.5
//                  }
//                }
//              ]
//            }
//          },
//          {
//            "key" : "WAN2",
//            "doc_count" : 10,
//            "my_graph" : {
//              "buckets" : [
//                {
//                  "key_as_string" : "2020-05-08T07:30:00.000Z",
//                  "key" : 1588923000000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 7829739.5
//                  },
//                  "totalBandwidth" : {
//                    "value" : 1.0E9
//                  },
//                  "inOctets" : {
//                    "value" : 1.60380961E8
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:32:00.000Z",
//                  "key" : 1588923120000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 7831352.5
//                  },
//                  "totalBandwidth" : {
//                    "value" : 1.0E9
//                  },
//                  "inOctets" : {
//                    "value" : 1.60418211E8
//                  },
//                  "as_difference_in" : {
//                    "value" : 37250.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 1613.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:34:00.000Z",
//                  "key" : 1588923240000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 7833824.5
//                  },
//                  "totalBandwidth" : {
//                    "value" : 1.0E9
//                  },
//                  "inOctets" : {
//                    "value" : 1.60458216E8
//                  },
//                  "as_difference_in" : {
//                    "value" : 40005.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 2472.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:36:00.000Z",
//                  "key" : 1588923360000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 7836296.5
//                  },
//                  "totalBandwidth" : {
//                    "value" : 1.0E9
//                  },
//                  "inOctets" : {
//                    "value" : 1.6049768E8
//                  },
//                  "as_difference_in" : {
//                    "value" : 39464.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 2472.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:38:00.000Z",
//                  "key" : 1588923480000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 7837946.5
//                  },
//                  "totalBandwidth" : {
//                    "value" : 1.0E9
//                  },
//                  "inOctets" : {
//                    "value" : 1.60533781E8
//                  },
//                  "as_difference_in" : {
//                    "value" : 36101.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 1650.0
//                  }
//                }
//              ]
//            }
//          },
//          {
//            "key" : "ether10",
//            "doc_count" : 10,
//            "my_graph" : {
//              "buckets" : [
//                {
//                  "key_as_string" : "2020-05-08T07:30:00.000Z",
//                  "key" : 1588923000000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:32:00.000Z",
//                  "key" : 1588923120000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:34:00.000Z",
//                  "key" : 1588923240000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:36:00.000Z",
//                  "key" : 1588923360000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:38:00.000Z",
//                  "key" : 1588923480000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                }
//              ]
//            }
//          },
//          {
//            "key" : "ether3",
//            "doc_count" : 10,
//            "my_graph" : {
//              "buckets" : [
//                {
//                  "key_as_string" : "2020-05-08T07:30:00.000Z",
//                  "key" : 1588923000000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:32:00.000Z",
//                  "key" : 1588923120000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:34:00.000Z",
//                  "key" : 1588923240000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:36:00.000Z",
//                  "key" : 1588923360000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:38:00.000Z",
//                  "key" : 1588923480000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                }
//              ]
//            }
//          },
//          {
//            "key" : "ether4",
//            "doc_count" : 10,
//            "my_graph" : {
//              "buckets" : [
//                {
//                  "key_as_string" : "2020-05-08T07:30:00.000Z",
//                  "key" : 1588923000000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:32:00.000Z",
//                  "key" : 1588923120000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:34:00.000Z",
//                  "key" : 1588923240000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:36:00.000Z",
//                  "key" : 1588923360000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:38:00.000Z",
//                  "key" : 1588923480000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                }
//              ]
//            }
//          },
//          {
//            "key" : "ether5",
//            "doc_count" : 10,
//            "my_graph" : {
//              "buckets" : [
//                {
//                  "key_as_string" : "2020-05-08T07:30:00.000Z",
//                  "key" : 1588923000000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:32:00.000Z",
//                  "key" : 1588923120000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:34:00.000Z",
//                  "key" : 1588923240000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:36:00.000Z",
//                  "key" : 1588923360000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:38:00.000Z",
//                  "key" : 1588923480000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                }
//              ]
//            }
//          },
//          {
//            "key" : "ether6",
//            "doc_count" : 10,
//            "my_graph" : {
//              "buckets" : [
//                {
//                  "key_as_string" : "2020-05-08T07:30:00.000Z",
//                  "key" : 1588923000000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:32:00.000Z",
//                  "key" : 1588923120000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:34:00.000Z",
//                  "key" : 1588923240000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:36:00.000Z",
//                  "key" : 1588923360000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                },
//                {
//                  "key_as_string" : "2020-05-08T07:38:00.000Z",
//                  "key" : 1588923480000,
//                  "doc_count" : 2,
//                  "outOctets" : {
//                    "value" : 0.0
//                  },
//                  "totalBandwidth" : {
//                    "value" : 0.0
//                  },
//                  "inOctets" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_in" : {
//                    "value" : 0.0
//                  },
//                  "as_difference_out" : {
//                    "value" : 0.0
//                  }
//                }
//              ]
//            }
//          }
//        ]
//      }
//    }
//  }
//}`
//
//	var snmpResponse AutoGenerated
//	err := json.NewDecoder(strings.NewReader(res)).Decode(&snmpResponse)
//	if err != nil {
//		fmt.Println("Some errror while decoding:: ", err.Error())
//	}
//	fmt.Println(len(snmpResponse.Aggregations.GetNestedInterfaces.ByInterfaces.SmallBuckets))
//	for _, hit := range snmpResponse.Aggregations.GetNestedInterfaces.ByInterfaces.SmallBuckets {
//			fmt.Println(hit)
//			fmt.Println("hello")
//		}
//		//for _, hit := range snmpResponse.GetNestedInterfaces {
//		//	res.ModelNumber = hit.Source.System.SysDescr
//		//	systemUptime := hit.Source.System.SysUpTime
//		//	i, err := strconv.ParseInt(systemUptime, 10, 64)
//		//	if err != nil {
//		//		fmt.Println(err)
//		//	}
//		fmt.Println(snmpResponse)
//		//xyz(res)
//
//}